initial commit

diff --git a/.github/workflows/build-rpm.yaml b/.github/workflows/build-rpm.yaml
--- a/.github/workflows/build-rpm.yaml
+++ b/.github/workflows/build-rpm.yaml
@@ -53,6 +53,16 @@ jobs:
     runs-on: ubuntu-latest
     needs: build-container
     steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+
+      - name: Before download - List rpm dir
+        run: |
+          TOPDIR=$(pwd)/rpmbuild
+          echo "Using RPM build directory: $TOPDIR"
+          ls
+          ls -R build/package/rpm || echo "Directory missing"
+
       - name: Download Container Artifact
         uses: actions/download-artifact@v4
         with:
@@ -68,10 +78,6 @@ jobs:
         run: |
           export GITHUB_REF_NAME=${{ github.ref_name }}
           export CONTAINER_REGISTRY=${{ env.CONTAINER_REGISTRY }}
-          
-      - name: Before download - List rpm dir
-        run: |
-          ls -R build/package/rpm || echo "Directory missing"
 
       - name: Build RPM
         run: |
@@ -80,16 +86,17 @@ jobs:
           mkdir -p $TOPDIR/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
 
           # Copy files into correct structure
-          ls -R build/package/rpm/SOURCES/
+          ls -R build/package/rpm
           cp build/package/rpm/SOURCES/el-wifi-automations.latest.tar $TOPDIR/SOURCES/
           cp build/package/rpm/SPECS/app.spec $TOPDIR/SPECS/
 
           # Optional: list contents for debugging
           #echo "Spec file:"
           #cat $TOPDIR/SPECS/app.spec
-
+          echo "Reached RPM Build"
+          ls -R $TOPDIR
           # Build RPM
-          rpmbuild --define "_topdir $TOPDIR" -bb SPECS/app.spec
+          rpmbuild --define "_topdir $TOPDIR" -bb $TOPDIR/SPECS/app.spec
 
       - name: Upload RPM Artifact
         uses: actions/upload-artifact@v4
