Workflow Debug

diff --git a/.github/workflows/build-rpm.yaml b/.github/workflows/build-rpm.yaml
--- a/.github/workflows/build-rpm.yaml
+++ b/.github/workflows/build-rpm.yaml
@@ -53,6 +53,10 @@ jobs:
     runs-on: ubuntu-latest
     needs: build-container
     steps:
+      - name: Before download - List rpm dir
+        run: |
+          ls -R build/package/rpm || echo "Directory missing"
+          
       - name: Download Container Artifact
         uses: actions/download-artifact@v4
         with:
@@ -68,10 +72,6 @@ jobs:
         run: |
           export GITHUB_REF_NAME=${{ github.ref_name }}
           export CONTAINER_REGISTRY=${{ env.CONTAINER_REGISTRY }}
-          
-      - name: Before download - List rpm dir
-        run: |
-          ls -R build/package/rpm || echo "Directory missing"
 
       - name: Build RPM
         run: |
